version: '3'
services:
  cseg-tools:
    build: .
    command: cseg-server
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data
    environment:
      - CSEG_DB_DIR=/data

  # 追加のサービス定義（必要に応じて使用）
  vcf2cseg:
    build: .
    command: vcf2cseg
    volumes:
      - ./data:/data

  create-db:
    build: .
    command: cseg-create-db
    volumes:
      - ./data:/data
