version: '1.0'
services:
  cseg-tools:
    build:
      context: .
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: cseg-server

  # 追加のサービス定義（必要に応じて使用）
  vcf2cseg:
    build:
      context: .
    volumes:
      - ./data:/data
    entrypoint: ["vcf2cseg"]
    profiles: ["tools"]  # docker-compose --profile tools up vcf2cseg で実行

  create-db:
    build:
      context: .
    volumes:
      - ./data:/data
    entrypoint: ["cseg-create-db"]
    profiles: ["tools"]  # docker-compose --profile tools up create-db で実行
